#cloud-config
package_update: true
package_upgrade: true

users:
  - name: ubuntu
    groups: [sudo, docker]
    shell: /bin/bash
    sudo: 'ALL=(ALL) NOPASSWD:ALL'
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHG7I/TEXSLjhxxLOnuCMEPYKnn6qVaO7psHffR2/G9l matvei31055@gmail.com

packages:
  - docker.io
  - docker-compose

write_files:
  - path: /home/ubuntu/docker-compose.yml
    content: |
      version: '3.8'
      services:
        nginx:
          image: nginx:alpine
          ports:
            - "80:80"
          restart: unless-stopped

  - path: /home/ubuntu/test.sh
    content: |
      #!/bin/bash
      echo "Cloud-init completed successfully at $(date)" > /home/ubuntu/cloud-init.log
      docker --version >> /home/ubuntu/cloud-init.log
      docker-compose --version >> /home/ubuntu/cloud-init.log
    permissions: '0755'

runcmd:
  - systemctl enable docker
  - systemctl start docker
  - chown -R ubuntu:ubuntu /home/ubuntu
  - su - ubuntu -c "cd /home/ubuntu && docker-compose up -d"
  - /home/ubuntu/test.sh

final_message: "Cloud-init completed successfully in $UPTIME seconds"